configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://neondb_owner:N4O8LMcWsBaD@ep-falling-pine-a5aps6pw.us-east-2.aws.neon.tech/neondb?sslmode=require
  - configuration:
      name: auth_config
      client_id: 95b574c898524f0f876f46f5eff8f2b4
      client_secret: 837ff6a2211244a28a4535529177a84c

